// 店铺管理原型数据
window.STORE_DATA = [
  {
    id: 1,
    platform: 'Shopee',
    name: 'Shopee MY 旗舰店',
    alias: '东南亚主力店',
    body: '云易盒科技有限公司',
    subName: '—',
    site: 'MY',
    region: '',
    storeType: '本土店',
    platformStoreType: '优选店铺',
    bu: '东南亚事业部',
    status: '启用',
    authStatus: '已授权',
    authTime: '2026-05-19 10:30',
    authExpire: '2027-05-19 10:30',
    authType: 'shop_account',
    mainAccountId: null,
    isSip: false,
    syncOrderTime: '2026-05-19 14:00',
    operator: '张三',
    cs: '王五',
    platformShopId: '12345',
    platformShopName: 'Main Store MY',
    merchantId: null,
    useStatus: '正常使用',
    enabled: true,
    cancelDate: null,
    dept: '东南亚事业部',
    owner: '张三',
    browserName: '紫鸟',
    browserStoreName: 'MY旗舰店浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    registrationDate: '2025-12-08',
    fundPlatform: 'PingPong',
    fundAccount: '**** **** 3821',
    fundAccountRaw: 'pingpong-my-3821@yiyihe.com',
    fundAccountId: 'PP-MY-3821',
    aeFreightAlipay: '',
    hasDeposit: true,
    depositRefundStatus: '未退回',
    depositAccount: '**** 9018',
    depositAccountRaw: 'deposit-my-9018',
    depositAmount: '12,000.00',
    depositRefundTime: '',
    depositRefundTransactionId: '',
    remarks: '主力经营店铺，订单同步频率较高。',
    adAuthStatus: '已授权',
    affiliateAuthStatus: '未授权',
    relatedStores: [],
    unrecordedStores: 0,
    storeEmail: 'shopee-my@yiyihe.com',
    paymentAccounts: [
      { platform: 'PingPong', account: '**** **** 3821', accountRaw: 'pingpong-my-3821@yiyihe.com', accountId: 'PP-MY-3821', currency: 'USD' },
      { platform: 'WorldFirst', account: '**** **** 6390', accountRaw: 'wf-my-6390@yiyihe.com', accountId: 'WF-MY-6390', currency: 'MYR' },
      { platform: '连连支付', account: '**** **** 2107', accountRaw: 'lianlian-my-2107@yiyihe.com', accountId: 'LL-MY-2107', currency: 'USD' }
    ],
    bodyChangeRecords: [
      { time: '2026-05-18 15:42', operator: 'Freddy', from: '云易盒贸易有限公司', to: '云易盒科技有限公司' },
      { time: '2026-04-02 10:16', operator: '张三', from: '云易盒跨境事业部', to: '云易盒贸易有限公司' }
    ],
    paymentChangeRecords: [
      { time: '2026-05-19 11:20', operator: 'Freddy', content: '新增 WorldFirst 收款账号 WF-MY-6390，用于 MYR 回款' },
      { time: '2026-05-18 16:05', operator: 'Freddy', content: '店铺主体变更后，主收款账号由 PingPong PP-OLD-9201 调整为 PP-MY-3821' },
      { time: '2026-04-10 09:36', operator: '张三', content: '新增连连支付备用收款账号 LL-MY-2107' }
    ],
    permissions: ['订单查看', '商品管理', '库存同步', '资金信息查看'],
    ops: ['详情', '编辑', '授权', '更多']
  },
  {
    id: 2,
    platform: 'Shopee',
    name: 'Shopee SG 专营店',
    alias: '新加坡店',
    body: '云易盒科技有限公司',
    subName: '—',
    site: 'SG',
    region: '',
    storeType: '跨境店（CNSC）',
    platformStoreType: '商城店铺',
    bu: '东南亚事业部',
    status: '启用',
    authStatus: '已授权',
    authTime: '2026-05-19 10:30',
    authExpire: '2027-05-19 10:30',
    authType: 'main_account',
    mainAccountId: 'main_acct_10001',
    isSip: false,
    syncOrderTime: '2026-05-19 14:00',
    operator: '张三',
    cs: '王五',
    platformShopId: '23456',
    platformShopName: 'CNSC Shop SG',
    merchantId: 'merchant_1001705',
    useStatus: '正常使用',
    enabled: true,
    cancelDate: null,
    dept: '东南亚事业部',
    owner: '张三',
    browserName: '紫鸟',
    browserStoreName: 'SG专营店浏览器',
    accountType: '购买',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    registrationDate: '2025-10-21',
    fundPlatform: 'WorldFirst',
    fundAccount: '**** **** 6679',
    fundAccountRaw: 'wf-sg-6679@yiyihe.com',
    fundAccountId: 'WF-SG-6679',
    aeFreightAlipay: '',
    hasDeposit: true,
    depositRefundStatus: '已退回',
    depositAccount: '**** 3302',
    depositAccountRaw: 'deposit-sg-3302',
    depositAmount: '8,000.00',
    depositRefundTime: '2026-04-18',
    depositRefundTransactionId: 'ALP202604180091',
    remarks: '通过主账号授权录入。',
    adAuthStatus: '已授权',
    affiliateAuthStatus: '已授权',
    relatedStores: ['Shopee MY 旗舰店', 'Shopee TH 跨境店'],
    unrecordedStores: 2,
    storeEmail: 'shopee-sg@yiyihe.com',
    paymentAccounts: [
      { platform: 'WorldFirst', account: '**** **** 6679', accountRaw: 'wf-sg-6679@yiyihe.com', accountId: 'WF-SG-6679', currency: 'SGD' },
      { platform: 'PingPong', account: '**** **** 8752', accountRaw: 'pingpong-sg-8752@yiyihe.com', accountId: 'PP-SG-8752', currency: 'USD' }
    ],
    bodyChangeRecords: [
      { time: '2026-05-17 14:10', operator: '李四', from: '云易盒科技香港有限公司', to: '云易盒科技有限公司' }
    ],
    paymentChangeRecords: [
      { time: '2026-05-17 14:18', operator: '李四', content: '主体变更后同步更新 WorldFirst 收款账号归属证明' },
      { time: '2026-05-12 18:02', operator: 'Freddy', content: '新增 PingPong 备用账号 PP-SG-8752' }
    ],
    permissions: ['订单查看', '商品管理', '资金信息查看'],
    ops: ['详情', '编辑', '授权', '更多']
  },
  {
    id: 3,
    platform: 'Shopee',
    name: 'Shopee TH 跨境店',
    alias: '泰国3PF',
    body: '云易盒科技有限公司',
    subName: '—',
    site: 'TH',
    region: '',
    storeType: '3PF',
    platformStoreType: '普通店铺',
    bu: '东南亚事业部',
    status: '启用',
    authStatus: '即将过期',
    authTime: '2025-06-01 09:00',
    authExpire: '2026-05-25 09:00',
    authType: 'main_account',
    mainAccountId: 'main_acct_10002',
    isSip: true,
    syncOrderTime: '2026-05-19 13:30',
    operator: '李四',
    cs: '赵六',
    platformShopId: '34567',
    platformShopName: '3PF Shop TH',
    merchantId: 'merchant_1001706',
    useStatus: '正常使用',
    enabled: true,
    cancelDate: null,
    dept: '东南亚事业部',
    owner: '李四',
    browserName: '战斧',
    browserStoreName: 'TH跨境店浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    registrationDate: '2025-09-02',
    fundPlatform: 'PingPong',
    fundAccount: '**** **** 7712',
    fundAccountRaw: 'pingpong-th-7712@yiyihe.com',
    fundAccountId: 'PP-TH-7712',
    aeFreightAlipay: '',
    hasDeposit: false,
    depositRefundStatus: '无需退回',
    depositAccount: '',
    depositAccountRaw: '',
    depositAmount: '',
    depositRefundTime: '',
    depositRefundTransactionId: '',
    remarks: 'SIP 店铺，库存推送需要关注授权到期。',
    adAuthStatus: '已授权',
    affiliateAuthStatus: '未授权',
    relatedStores: ['Shopee SG 专营店'],
    unrecordedStores: 0,
    ops: ['详情', '编辑', '授权', '更多']
  },
  {
    id: 4,
    platform: 'Amazon',
    name: 'Amazon US Store',
    alias: '美国站',
    body: '云易盒科技美国',
    subName: '—',
    site: 'US',
    region: '北美',
    storeType: '本土店',
    platformStoreType: '专业卖家',
    bu: '北美事业部',
    status: '启用',
    authStatus: '已授权',
    authTime: '2026-03-01 10:00',
    authExpire: '2027-03-01 10:00',
    authType: null,
    mainAccountId: null,
    isSip: false,
    syncOrderTime: '2026-05-19 12:00',
    operator: '陈七',
    cs: '周八',
    platformShopId: 'A1B2C3',
    platformShopName: 'US Store',
    merchantId: null,
    useStatus: '正常使用',
    enabled: true,
    cancelDate: null,
    dept: '北美事业部',
    owner: '陈七',
    browserName: '紫鸟',
    browserStoreName: 'Amazon US 浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技美国',
    registrationDate: '2024-12-12',
    fundPlatform: 'Payoneer',
    fundAccount: '**** **** 1209',
    fundAccountRaw: 'payoneer-us-1209@yiyihe.com',
    fundAccountId: 'PY-US-1209',
    aeFreightAlipay: '',
    hasDeposit: false,
    depositRefundStatus: '无需退回',
    depositAccount: '',
    depositAccountRaw: '',
    depositAmount: '',
    depositRefundTime: '',
    depositRefundTransactionId: '',
    remarks: 'Amazon SP-API 授权店铺。',
    adAuthStatus: '已授权',
    affiliateAuthStatus: '未授权',
    relatedStores: [],
    unrecordedStores: 0,
    ops: ['详情', '编辑', '更多']
  },
  {
    id: 5,
    platform: 'Shopee',
    name: '—',
    alias: '待授权新店',
    body: '云易盒科技有限公司',
    subName: '—',
    site: 'VN',
    region: '',
    storeType: '本土店',
    platformStoreType: '—',
    bu: '东南亚事业部',
    status: '停用',
    authStatus: '未授权',
    authTime: '—',
    authExpire: '—',
    authType: null,
    mainAccountId: null,
    isSip: false,
    syncOrderTime: '—',
    operator: '—',
    cs: '—',
    platformShopId: null,
    platformShopName: null,
    merchantId: null,
    useStatus: '待授权',
    enabled: false,
    cancelDate: null,
    dept: '东南亚事业部',
    owner: '—',
    browserName: '',
    browserStoreName: '',
    accountType: '',
    registrationType: '',
    registrationCompany: '',
    registrationDate: '',
    fundPlatform: '',
    fundAccount: '',
    fundAccountRaw: '',
    fundAccountId: '',
    aeFreightAlipay: '',
    hasDeposit: false,
    depositRefundStatus: '无需退回',
    depositAccount: '',
    depositAccountRaw: '',
    depositAmount: '',
    depositRefundTime: '',
    depositRefundTransactionId: '',
    remarks: '待完成 Shopee 授权。',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    relatedStores: [],
    unrecordedStores: 0,
    ops: ['详情', '编辑', '授权', '更多']
  },
  {
    id: 6,
    platform: 'TikTok Shop',
    name: 'TikTok ID 官方店',
    alias: '印尼内容店',
    body: '云易盒科技有限公司',
    subName: '—',
    site: 'ID',
    region: '',
    storeType: '跨境店',
    platformStoreType: 'Mall',
    bu: '东南亚事业部',
    status: '启用',
    authStatus: '已授权',
    authTime: '2026-05-10 11:00',
    authExpire: '2027-05-10 11:00',
    authType: 'oauth',
    mainAccountId: null,
    isSip: false,
    syncOrderTime: '2026-05-19 13:00',
    operator: '李四',
    cs: '赵六',
    platformShopId: 'TTS-77881',
    platformShopName: 'TikTok ID Official',
    merchantId: null,
    useStatus: '正常使用',
    enabled: true,
    cancelDate: null,
    dept: '东南亚事业部',
    owner: '李四',
    storeEmail: 'tiktok-id@yiyihe.com',
    adAccountId: 'act_73910288',
    bcId: 'bc_448201',
    browserName: '紫鸟',
    browserStoreName: 'TikTok ID 浏览器',
    accountType: '自注册',
    registrationType: '企业',
    registrationCompany: '云易盒科技有限公司',
    registrationDate: '2026-01-18',
    fundPlatform: 'PingPong',
    fundAccount: '**** **** 9021',
    fundAccountRaw: 'pingpong-tt-9021@yiyihe.com',
    fundAccountId: 'PP-TT-9021',
    aeFreightAlipay: '',
    hasDeposit: false,
    depositRefundStatus: '无需退回',
    depositAccount: '',
    depositAccountRaw: '',
    depositAmount: '',
    depositRefundTime: '',
    depositRefundTransactionId: '',
    remarks: 'TikTok 广告授权后需设置广告数据更新时段。',
    adAuthStatus: '未授权',
    affiliateAuthStatus: '未授权',
    relatedStores: [],
    unrecordedStores: 0,
    paymentAccounts: [
      { platform: 'PingPong', account: '**** **** 9021', accountRaw: 'pingpong-tt-9021@yiyihe.com', accountId: 'PP-TT-9021', currency: 'USD' },
      { platform: 'WorldFirst', account: '**** **** 1188', accountRaw: 'wf-tt-1188@yiyihe.com', accountId: 'WF-TT-1188', currency: 'IDR' }
    ],
    bodyChangeRecords: [
      { time: '2026-05-12 09:20', operator: 'Freddy', from: '云易盒贸易有限公司', to: '云易盒科技有限公司' }
    ],
    paymentChangeRecords: [
      { time: '2026-05-18 16:30', operator: 'Freddy', content: '新增 WorldFirst 收款账号 WF-TT-1188' }
    ],
    permissions: ['订单查看', '商品管理', '库存同步'],
    adSyncSetting: null,
    ops: ['详情', '编辑', '授权', '更多']
  }
];

// 授权状态标签映射
window.AUTH_STATUS_MAP = {
  '已授权':   { tag: 'tag-green',  text: '已授权' },
  '即将过期':  { tag: 'tag-orange', text: '即将过期' },
  '已过期':   { tag: 'tag-red',    text: '已过期' },
  '未授权':   { tag: 'tag-gray',   text: '未授权' },
  'Token失效': { tag: 'tag-red',    text: 'Token 失效' },
};
